# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 103940bc2260ed55378ea2097d3c3ae318d5edd86c6df15a1799e36be116c9d7603678656244eaee18211e2c5bfcf6ea47252e941a936d5505cf84eef4907e07

test:
  secret_key_base: 41c931307bbf9090f282356c6257d793a6878a389555228c2ad0e74aa541c1354fcb004380c3e32ebd8dcbd6727d0b70d2722924280fe7d4ce5d1f4b26e70d2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
